[package]
name = "tinysql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.10.0"
rayon = "1.10.0"
rusqlite = "0.31.0"
serde = "1.0.203"
serde_json = "1.0.120"
tide = "0.16.0"
tiny_http = "0.12.0"
