[package]
name = "tinysql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
rayon = "1.10.0"
serde = "1.0.203"
serde_json = "1.0.120"
sqlx = { version = "0.7", features = ["sqlite", "runtime-async-std-native-tls"] }
tiny_http = "0.12.0"
